<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MatthL.ResultLogger.Core\MatthL.ResultLogger.Core.csproj" />
    <ProjectReference Include="..\MatthL.ResultLogger.UI\MatthL.ResultLogger.UI.csproj" />
  </ItemGroup>

</Project>
